function trackers = config_tracker()
% config trackers to be evaluated
trackers = {struct('name', 'ARTrack',           'publish', '-') ...
            struct('name', 'ATOM',              'publish', '-') ...
            struct('name', 'AutoMatch',         'publish', '-') ...
            struct('name', 'DiMP',              'publish', '-') ...
            struct('name', 'DropMAE',           'publish', '-') ...
            struct('name', 'GRM',               'publish', '-') ...
            struct('name', 'Ocean',             'publish', '-') ...
            struct('name', 'MixFormer',         'publish', '-') ...
            struct('name', 'MixFormerV2',       'publish', '-') ...
            struct('name', 'OSTrack',           'publish', '-') ...
            struct('name', 'PrDiMP',            'publish', '-') ...
            struct('name', 'ROMTrack',          'publish', '-') ...
            struct('name', 'RTS',               'publish', '-') ...
            struct('name', 'SeqTrack',          'publish', '-') ...
            struct('name', 'SiamBAN',           'publish', '-') ...
            struct('name', 'SiamCAR',           'publish', '-') ...
            struct('name', 'SiamFC',            'publish', '-') ...
            struct('name', 'SiamRPN++',         'publish', '-') ...
            struct('name', 'SimTrack',          'publish', '-') ...
            struct('name', 'STARK',             'publish', '-') ...
            struct('name', 'STMTrack',          'publish', '-') ...
            struct('name', 'ToMP',              'publish', '-') ...
            struct('name', 'TransT',            'publish', '-') ...
            struct('name', 'TrSiam',            'publish', '-') ...
            struct('name', 'SwinTrack',         'publish', '-') ...
            };

end